version: "3"
services:
  message_broker:
    image: rabbitmq:latest
    hostname: rabbit
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      djangoAsynchronous:
        aliases:
          - rabbit
    volumes:
      - broker_volume:/var/lib/rabbitmq/
  tasks:
    image: app
    command: >
      celery 
        --broker amqp://guest:guest@rabbit:5672// 
        --app django_asynchronous
        worker
        --loglevel=INFO
    environment:
      - DATA_SOURCE_PATH=data_source/
    depends_on:
      - message_broker
    networks:
      - djangoAsynchronous
    volumes:
      - ./:/djangoAsynchronous
  app:
    image: app
    ports:
      - 8000:8000
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - message_broker
      - tasks
    networks:
      djangoAsynchronous:
        aliases:
          - app
    volumes:
      - ./:/djangoAsynchronous

networks:
  djangoAsynchronous:

volumes:
  broker_volume:

